services:
  i2t-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: http://localhost:8000/api/process_image # 后端接口地址，根据实际情况修改
    ports:
      - "8080:80"
    restart: always # 确保服务始终运行
